(function(g){var window=this;'use strict';var Dhb=function(a,b){a.Qa("onAutonavCoundownStarted",b)},j6=function(a,b,c){g.Cq(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Ig(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.UN&&(b.lengthText?(e=b.lengthText||null,f=b.Rv||null):b.lengthSeconds&&(e=g.NR(b.lengthSeconds),f=g.NR(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.SN(d).type;var l=b instanceof g.UN?b.isLivePlayback:null,m=b instanceof g.UN?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],v=[];n&&r.push(n);p&&(r.push(p),v.push(p));q&&v.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.VP("Ver $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Mk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:v.join(" \u2022 "),autoplayAlternativeHeader:b.ls};b instanceof g.TN&&(c.playlist_length=b.playlistLength);a.update(c)},k6=function(a){var b=a.W(),c=b.C;
g.X.call(this,{G:"a",S:"ytp-autonav-suggestion-card",Y:{href:"{{url}}",target:c?b.ma:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},X:[{G:"div",Ma:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],Y:{style:"{{background}}"},X:[{G:"div",Y:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],Aa:"{{duration}}"},{G:"div",Ma:["ytp-autonav-live-stamp"],Aa:"En vivo"},
{G:"div",Ma:["ytp-autonav-upcoming-stamp"],Aa:"Pr\u00f3ximamente"},{G:"div",S:"ytp-autonav-list-overlay",X:[{G:"div",S:"ytp-autonav-mix-text",Aa:"Mix"},{G:"div",S:"ytp-autonav-mix-icon"}]}]},{G:"div",Ma:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Aa:"{{title}}"},{G:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Aa:"{{author}}"},{G:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Aa:"{{views_and_publish_time}}"}]});this.I=
a;this.suggestion=null;this.j=c;this.Ua("click",this.onClick);this.Ua("keypress",this.onKeyPress)},l6=function(a,b){b=void 0===b?!1:b;
g.X.call(this,{G:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.J=b;this.D=void 0;this.B=0;this.container=new g.X({G:"div",S:"ytp-autonav-endscreen-countdown-container"});g.G(this,this.container);this.container.Ia(this.element);b=a.W();var d=b.C;this.I=a;this.suggestion=null;this.onVideoDataChange("newdata",this.I.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.X({G:"div",S:"ytp-autonav-endscreen-upnext-container",Y:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},X:[{G:"div",S:"ytp-autonav-endscreen-upnext-header"},{G:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",Aa:"{{autoplayAlternativeHeader}}"},{G:"a",S:"ytp-autonav-endscreen-link-container",Y:{href:"{{url}}",target:d?b.ma:""},X:[{G:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",Y:{style:"{{background}}"},X:[{G:"div",Y:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],
Aa:"{{duration}}"},{G:"div",Ma:["ytp-autonav-live-stamp"],Aa:"En vivo"},{G:"div",Ma:["ytp-autonav-upcoming-stamp"],Aa:"Pr\u00f3ximamente"}]},{G:"div",S:"ytp-autonav-endscreen-video-info",X:[{G:"div",S:"ytp-autonav-endscreen-premium-badge"},{G:"div",S:"ytp-autonav-endscreen-upnext-title",Aa:"{{title}}"},{G:"div",S:"ytp-autonav-endscreen-upnext-author",Aa:"{{author}}"},{G:"div",S:"ytp-autonav-view-and-date",Aa:"{{views_and_publish_time}}"},{G:"div",S:"ytp-autonav-author-and-view",Aa:"{{author_and_views}}"}]}]}]});
g.G(this,this.j);this.j.Ia(this.container.element);d||this.T(this.j.Ha("ytp-autonav-endscreen-link-container"),"click",this.pR);this.I.xb(this.container.element,this,115127);this.I.xb(this.j.Ha("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.X({G:"div",S:"ytp-autonav-overlay"});g.G(this,this.overlay);this.overlay.Ia(this.container.element);this.u=new g.X({G:"div",S:"ytp-autonav-endscreen-button-container"});g.G(this,this.u);this.u.Ia(this.container.element);this.cancelButton=
new g.X({G:"button",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{"aria-label":"Cancelar reproducci\u00f3n autom\u00e1tica"},Aa:"Cancelar"});g.G(this,this.cancelButton);this.cancelButton.Ia(this.u.element);this.cancelButton.Ua("click",this.L_,this);this.I.xb(this.cancelButton.element,this,115129);this.playButton=new g.X({G:"a",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{href:"{{url}}",role:"button","aria-label":"Reproducir siguiente video"},Aa:"Reproducir ahora"});g.G(this,this.playButton);this.playButton.Ia(this.u.element);this.playButton.Ua("click",this.pR,this);this.I.xb(this.playButton.element,this,115130);this.C=new g.qq(function(){Ehb(c)},500);
g.G(this,this.C);this.oR();this.T(a,"autonavvisibility",this.oR);this.I.N("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.K_),this.T(a,"onAutonavCoundownStarted",this.p6))},m6=function(a){var b=a.I.Lk(!0,a.I.isFullscreen());
g.Cq(a.container.element,"ytp-autonav-endscreen-small-mode",a.jh(b));g.Cq(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.RI);g.Cq(a.I.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.I.Kf());g.Cq(a.I.getRootNode(),"countdown-running",a.Qk());g.Cq(a.container.element,"ytp-player-content",a.I.Kf());g.qn(a.overlay.element,{width:b.width+"px"});if(!a.Qk()){a.I.Kf()?Fhb(a,Math.round(Ghb(a)/1E3)):Fhb(a);b=!!a.suggestion&&!!a.suggestion.ls;var c=a.I.Kf()||!b;
g.Cq(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.Cq(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.fR(a.u,a.I.Kf());g.Cq(a.element,"ytp-enable-w2w-color-transitions",Hhb(a))}},Ehb=function(a){var b=Ghb(a),c=Math,d=c.min;
var e=a.B?Date.now()-a.B:0;c=d.call(c,e,b);Fhb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Qk()?a.select(!0):a.Qk()&&a.C.start()},Ghb=function(a){if(a.I.isFullscreen()){var b;
a=null==(b=a.I.getVideoData())?void 0:b.QE;return-1===a||void 0===a?8E3:a}return 0<=a.I.Ks()?a.I.Ks():g.nL(a.I.W().experiments,"autoplay_time")||1E4},Hhb=function(a){var b;
return!(null==(b=a.I.getVideoData())||!b.watchToWatchTransitionRenderer)},Fhb=function(a,b){b=void 0===b?-1:b;
a=a.j.Ha("ytp-autonav-endscreen-upnext-header");g.ff(a);if(0<=b){b=String(b);var c="A continuaci\u00f3n, en $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="A continuaci\u00f3n, en $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.df("A continuaci\u00f3n, en $SECONDS".slice(0,d)));var e=g.cf("span");g.wq(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.qf(e,b);a.appendChild(e);a.appendChild(g.df("A continuaci\u00f3n, en $SECONDS".slice(d+c.length)));return}}g.qf(a,"Siguiente")},n6=function(a,
b){g.X.call(this,{G:"div",
Ma:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},o6=function(a){g.X.call(this,{G:"div",
Ma:["ytp-upnext","ytp-player-content"],Y:{"aria-label":"{{aria_label}}"},X:[{G:"div",S:"ytp-cued-thumbnail-overlay-image",Y:{style:"{{background}}"}},{G:"span",S:"ytp-upnext-top",X:[{G:"span",S:"ytp-upnext-header",Aa:"A continuaci\u00f3n"},{G:"span",S:"ytp-upnext-title",Aa:"{{title}}"},{G:"span",S:"ytp-upnext-author",Aa:"{{author}}"}]},{G:"a",S:"ytp-upnext-autoplay-icon",Y:{role:"button",href:"{{url}}","aria-label":"Reproducir siguiente video"},X:[{G:"svg",Y:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},X:[{G:"circle",S:"ytp-svg-autoplay-circle",Y:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",S:"ytp-svg-autoplay-ring",Y:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",S:"ytp-svg-fill",Y:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",S:"ytp-upnext-bottom",X:[{G:"span",S:"ytp-upnext-cancel"},{G:"span",S:"ytp-upnext-paused",
Aa:"La reproducci\u00f3n autom\u00e1tica est\u00e1 en pausa"}]}]});this.api=a;this.cancelButton=null;this.D=this.Ha("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.qq(this.KF,5E3,this);this.u=0;var b=this.Ha("ytp-upnext-cancel");this.cancelButton=new g.X({G:"button",Ma:["ytp-upnext-cancel-button","ytp-button"],Y:{tabindex:"0","aria-label":"Cancelar reproducci\u00f3n autom\u00e1tica"},Aa:"Cancelar"});g.G(this,this.cancelButton);this.cancelButton.Ua("click",
this.M_,this);this.cancelButton.Ia(b);this.cancelButton&&this.api.xb(this.cancelButton.element,this,115129);g.G(this,this.C);this.api.xb(this.element,this,18788);b=this.Ha("ytp-upnext-autoplay-icon");this.T(b,"click",this.N_);this.api.xb(b,this,115130);this.qR();this.T(a,"autonavvisibility",this.qR);this.T(a,"mdxnowautoplaying",this.Y6);this.T(a,"mdxautoplaycanceled",this.Z6);g.Cq(this.element,"ytp-upnext-mobile",this.api.W().u)},Ihb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.QE;return-1===a||void 0===a?8E3:a}return 0<=a.api.Ks()?a.api.Ks():g.nL(a.api.W().experiments,"autoplay_time")||1E4},Jhb=function(a,b){b=Ihb(a,b);
var c=Math,d=c.min;var e=(0,g.EB)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Qk()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Qk()&&a.j.start()},p6=function(a){n6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.X({G:"div",S:"ytp-suggestion-panel",X:[{G:"div",Ma:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Aa:"M\u00e1s videos"}]});this.K=new g.X({G:"div",S:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.J=!1;this.u=new l6(this.player);g.G(this,this.u);this.u.Ia(this.element);a.getVideoData().Re?this.j=this.u:(this.j=new o6(a),g.cT(this.player,this.j.element,4),g.G(this,this.j));this.overlay=new g.X({G:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.G(this,this.overlay);this.overlay.Ia(this.element);this.C=new g.fK(this);g.G(this,this.C);g.G(this,this.table);this.table.Ia(this.element);this.table.show();g.G(this,this.K);this.K.Ia(this.table.element);this.hide()},q6=function(a){var b=a.Kf();
b!==a.D&&(a.D=b,a.player.qa("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},r6=function(a,b){g.X.call(this,{G:"button",
Ma:["ytp-watch-on-youtube-button","ytp-button"],Aa:"{{content}}"});this.I=a;this.buttonType=this.buttonType=b;b=this.I.getVideoData();if(a.N("embeds_enable_server_driven_watch_again_on_youtube")){var c,d;if(c=(a=null==(c=b.Bd)?void 0:null==(d=c.playerOverlays)?void 0:d.playerOverlayRenderer)&&g.R(a.watchOnYoutubeButton,g.EKa))this.j=c}if(this.j)this.update({content:this.j.title}),this.I.Wf(this.element,this),this.I.eg(this.element,this.j.trackingParams||null);else{switch(this.buttonType){case 1:c=
"Mirar de nuevo en YouTube";d=156915;break;case 2:c="Seguir mirando en YouTube";d=156942;break;default:c="Seguir mirando en YouTube",d=156942}this.update({content:c});this.I.xb(this.element,this,d)}2===this.buttonType&&g.yq(this.element,"ytp-continue-watching-button");this.Ua("click",this.onClick);g.fR(this,!0)},s6=function(a,b){n6.call(this,a,"embeds-lite-endscreen");
this.I=a;this.j=b;this.I.xb(this.element,this,156943);this.watchButton=new r6(a,2);g.G(this,this.watchButton);this.watchButton.Ia(this.element);this.hide()},Khb=function(a){n6.call(this,a,"subscribecard-endscreen");
this.j=new g.X({G:"div",S:"ytp-subscribe-card",X:[{G:"img",S:"ytp-author-image",Y:{src:"{{profilePicture}}"}},{G:"div",S:"ytp-subscribe-card-right",X:[{G:"div",S:"ytp-author-name",Aa:"{{author}}"},{G:"div",S:"html5-subscribe-button-container"}]}]});g.G(this,this.j);this.j.Ia(this.element);var b=a.getVideoData();this.subscribeButton=new g.MU("Suscribirse",null,"Anular suscripci\u00f3n",null,!0,!1,b.vk,b.subscribed,"trailer-endscreen",null,a);g.G(this,this.subscribeButton);this.subscribeButton.Ia(this.j.Ha("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ta);this.Ta();this.hide()},t6=function(a){var b=a.W(),c=g.iK||g.pM?{style:"will-change: opacity"}:void 0,d=b.C,e=["ytp-videowall-still"];
b.u&&e.push("ytp-videowall-show-text");g.X.call(this,{G:"a",Ma:e,Y:{href:"{{url}}",target:d?b.ma:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},X:[{G:"div",S:"ytp-videowall-still-image",Y:{style:"{{background}}"}},{G:"span",S:"ytp-videowall-still-info",Y:{"aria-hidden":"true"},X:[{G:"span",S:"ytp-videowall-still-info-bg",X:[{G:"span",S:"ytp-videowall-still-info-content",Y:c,X:[{G:"span",S:"ytp-videowall-still-info-title",Aa:"{{title}}"},
{G:"span",S:"ytp-videowall-still-info-author",Aa:"{{author_and_views}}"},{G:"span",S:"ytp-videowall-still-info-live",Aa:"En vivo"},{G:"span",S:"ytp-videowall-still-info-duration",Aa:"{{duration}}"}]}]}]},{G:"span",Ma:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},X:[{G:"span",S:"ytp-videowall-still-listlabel-icon"},"Lista de reproducci\u00f3n",{G:"span",S:"ytp-videowall-still-listlabel-length",X:[" (",{G:"span",Aa:"{{playlist_length}}"},")"]}]},
{G:"span",Ma:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},X:[{G:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",S:"ytp-videowall-still-listlabel-length",Aa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.fK(this);g.G(this,this.j);this.Ua("click",this.onClick);this.Ua("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.Wf(this.element,this);this.onVideoDataChange()},u6=function(a){n6.call(this,
a,"videowall-endscreen");
var b=this;this.I=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.K=!1;this.V=null;this.u=new g.fK(this);g.G(this,this.u);this.J=new g.qq(function(){g.yq(b.element,"ytp-show-tiles")},0);
g.G(this,this.J);var c=new g.X({G:"button",Ma:["ytp-button","ytp-endscreen-previous"],Y:{"aria-label":"Anterior"},X:[g.jR()]});g.G(this,c);c.Ia(this.element);c.Ua("click",this.R_,this);this.table=new g.cR({G:"div",S:"ytp-endscreen-content"});g.G(this,this.table);this.table.Ia(this.element);c=new g.X({G:"button",Ma:["ytp-button","ytp-endscreen-next"],Y:{"aria-label":"Siguiente"},X:[g.kR()]});g.G(this,c);c.Ia(this.element);c.Ua("click",this.Q_,this);a.getVideoData().Re?this.j=new l6(a,!0):this.j=new o6(a);
g.G(this,this.j);g.cT(this.player,this.j.element,4);a.xb(this.element,this,158789);this.hide()},v6=function(a){return g.dT(a.player)&&a.nB()&&!a.C},w6=function(a){var b=a.Kf();
b!==a.K&&(a.K=b,a.player.qa("autonavvisibility"))},x6=function(a){n6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new r6(a,1);g.G(this,this.watchButton);this.watchButton.Ia(this.element);g.b9a(a)&&(this.j=new g.g3(a,g.MS(a)),g.G(this,this.j),this.u=new g.X({G:"div",Ma:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],Y:{tabIndex:"-1"},X:[this.j]}),g.G(this,this.u),this.j.Ia(this.u.element),this.u.Ia(this.element));a.xb(this.element,this,156914);this.hide()},Ohb=function(a){g.dU.call(this,a);
var b=this;this.endScreen=null;this.u=this.j=this.B=this.C=!1;this.listeners=new g.fK(this);g.G(this,this.listeners);var c=a.W(),d=a.getVideoData();d=d&&0!==d.endSeconds;g.jA(g.IM(c))&&d&&!g.ZS(a)?(this.u=!0,this.endScreen=new s6(a,g.MS(a))):g.$S(a)?this.endScreen=new x6(a):Lhb(a)?(this.C=!0,Mhb(this),this.j?this.endScreen=new p6(a):this.endScreen=new u6(a)):c.Ch?this.endScreen=new Khb(a):this.endScreen=new n6(a);g.G(this,this.endScreen);g.cT(a,this.endScreen.element,4);Nhb(this);this.listeners.T(a,
"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.$F("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.aG("endscreen"),function(e){b.onCueRangeExit(e)})},Mhb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Fl&&a.B===b.Re)return!1;a.j=b.Fl;a.B=b.Re;return!0},Lhb=function(a){a=a.W();
return a.Cd&&!a.Ch},Nhb=function(a){a.player.Oe("endscreen");
var b=a.player.getVideoData();b=new g.YF(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.YF(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.cf([b,c])};
g.BW.prototype.aA=g.da(36,function(a){this.YO!==a&&(this.YO=a,this.Al())});
g.pV.prototype.Br=g.da(35,function(a){this.u!==a&&(this.u=a,this.Ta())});
g.BW.prototype.Br=g.da(34,function(a){this.shareButton&&this.shareButton.Br(a)});
g.lV.prototype.Ar=g.da(33,function(a){this.j!==a&&(this.j=a,this.Ta())});
g.BW.prototype.Ar=g.da(32,function(a){this.overflowButton&&this.overflowButton.Ar(a)});
g.DU.prototype.oE=g.da(31,function(a){this.ZO!==a&&(this.ZO=a,this.Lp())});
g.VS.prototype.Ks=g.da(5,function(){return this.app.Ks()});
g.p_.prototype.Ks=g.da(4,function(){return this.getVideoData().JS});g.x(k6,g.X);k6.prototype.select=function(){this.I.jo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.JB||void 0)&&this.I.ub(this.element)};
k6.prototype.onClick=function(a){g.sT(a,this.I,this.j,this.suggestion.sessionData||void 0)&&this.select()};
k6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.cQ(a)||(this.select(),g.dQ(a))}};g.x(l6,g.X);g.k=l6.prototype;g.k.bF=function(a){this.suggestion!==a&&(this.suggestion=a,j6(this.j,a),this.playButton.updateValue("url",this.suggestion.Mk()),m6(this))};
g.k.Qk=function(){return 0<this.B};
g.k.iA=function(){this.Qk()||(this.B=Date.now(),Ehb(this),Dhb(this.I,Ghb(this)),g.Cq(this.I.getRootNode(),"countdown-running",this.Qk()))};
g.k.lw=function(){this.Hr();Ehb(this);var a=this.j.Ha("ytp-autonav-endscreen-upnext-header");a&&g.qf(a,"Siguiente")};
g.k.Hr=function(){this.Qk()&&(this.C.stop(),this.B=0)};
g.k.select=function(a){this.I.nextVideo(!1,void 0===a?!1:a);this.Hr()};
g.k.pR=function(a){g.sT(a,this.I)&&(a.currentTarget===this.playButton.element?this.I.ub(this.playButton.element):a.currentTarget===this.j.Ha("ytp-autonav-endscreen-link-container")&&(a=this.j.Ha("ytp-autonav-endscreen-link-container"),this.I.Za(a,!0),this.I.ub(a)),this.select())};
g.k.L_=function(){this.I.ub(this.cancelButton.element);g.XS(this.I,!0);this.D&&this.I.Qa("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.n2)?void 0:c.command};
g.k.p6=function(a){if(Hhb(this)){var b=this.I.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.UR(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.UR(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.UR(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.UR(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.UR(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.UR(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.Cq(this.element,"ytp-w2w-animate",!0)}};
g.k.K_=function(a){this.I.N("web_autonav_color_transition")&&2!==a&&g.Cq(this.element,"ytp-w2w-animate",!1)};
g.k.oR=function(){var a=this.I.Kf();this.J&&this.Fb!==a&&g.fR(this,a);m6(this);this.I.Za(this.container.element,a);this.I.Za(this.cancelButton.element,a);this.I.Za(this.j.Ha("ytp-autonav-endscreen-link-container"),a);this.I.Za(this.playButton.element,a)};
g.k.jh=function(a){return 400>a.width||459>a.height};g.x(n6,g.X);g.k=n6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.nB=function(){return!1};
g.k.Kf=function(){return!1};
g.k.SV=function(){return!1};g.x(o6,g.X);g.k=o6.prototype;g.k.KF=function(){this.notification&&(this.C.stop(),this.Kc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.bF=function(a){this.suggestion=a;j6(this,a,"hqdefault.jpg")};
g.k.qR=function(){g.fR(this,this.api.Kf());this.api.Za(this.element,this.api.Kf());this.api.Za(this.Ha("ytp-upnext-autoplay-icon"),this.api.Kf());this.cancelButton&&this.api.Za(this.cancelButton.element,this.api.Kf())};
g.k.h7=function(){window.focus();this.KF()};
g.k.iA=function(a){var b=this;this.Qk()||(g.kD("a11y-announce","A continuaci\u00f3n "+this.suggestion.title),this.u=(0,g.EB)(),this.j=new g.qq(function(){Jhb(b,a)},25),Jhb(this,a),Dhb(this.api,Ihb(this,a)));
g.Aq(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.X.prototype.hide.call(this)};
g.k.Qk=function(){return!!this.j};
g.k.lw=function(){this.Hr();this.u=(0,g.EB)();Jhb(this);g.yq(this.element,"ytp-upnext-autoplay-paused")};
g.k.Hr=function(){this.Qk()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.W().N("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.KF(),this.notification=new Notification("A continuaci\u00f3n",{body:this.suggestion.title,icon:this.suggestion.Ig()}),this.B=this.T(this.notification,"click",this.h7),this.C.start())}this.Hr();this.api.nextVideo(!1,a)};
g.k.N_=function(a){!g.pf(this.cancelButton.element,g.bQ(a))&&g.sT(a,this.api)&&(this.api.Kf()&&this.api.ub(this.Ha("ytp-upnext-autoplay-icon")),this.select())};
g.k.M_=function(){this.api.Kf()&&this.cancelButton&&this.api.ub(this.cancelButton.element);g.XS(this.api,!0)};
g.k.Y6=function(a){this.api.getPresentingPlayerType();this.show();this.iA(a)};
g.k.Z6=function(){this.api.getPresentingPlayerType();this.Hr();this.hide()};
g.k.xa=function(){this.Hr();this.KF();g.X.prototype.xa.call(this)};g.x(p6,n6);g.k=p6.prototype;g.k.create=function(){n6.prototype.create.call(this);this.C.T(this.player,"appresize",this.QA);this.C.T(this.player,"onVideoAreaChange",this.QA);this.C.T(this.player,"videodatachange",this.onVideoDataChange);this.C.T(this.player,"autonavchange",this.rR);this.C.T(this.player,"autonavcancel",this.O_);this.onVideoDataChange()};
g.k.show=function(){n6.prototype.show.call(this);(this.J||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.XS(this.player,!1);g.dT(this.player)&&this.nB()&&!this.B?(q6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.iA():3===this.videoData.autonavState&&this.j.lw()):(g.XS(this.player,!0),q6(this));this.QA()};
g.k.hide=function(){n6.prototype.hide.call(this);this.j.lw();q6(this)};
g.k.QA=function(){var a=this.player.Lk(!0,this.player.isFullscreen());q6(this);m6(this.u);g.Cq(this.element,"ytp-autonav-cancelled-small-mode",this.jh(a));g.Cq(this.element,"ytp-autonav-cancelled-tiny-mode",this.YG(a));g.Cq(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.qn(this.overlay.element,{width:a.width+"px"});if(!this.D)for(a=0;a<this.videos.length;a++)g.Cq(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.N("web_player_autonav_empty_suggestions_fix")){var b=g.AO(this.videoData);b&&(this.j.bF(b),this.j!==this.u&&this.u.bF(b))}if(a&&a.length)for(b=0;b<Phb.length;++b){var c=Phb[b];if(a&&a[c]){this.videos[b]=new k6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,j6(d,c));g.G(this,this.videos[b]);this.videos[b].Ia(this.K.element)}}this.QA()}};
g.k.rR=function(a){1===a?(this.J=!1,this.B=this.videoData.clientPlaybackNonce,this.j.Hr(),this.Fb&&this.QA()):(this.J=!0,this.Kf()&&(2===a?this.j.iA():3===a&&this.j.lw()))};
g.k.O_=function(a){a?this.rR(1):(this.B=null,this.J=!1)};
g.k.nB=function(){return 1!==this.videoData.autonavState};
g.k.jh=function(a){return(910>a.width||459>a.height)&&!this.YG(a)&&!(400>=a.width||360>=a.height)};
g.k.YG=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Kf=function(){return this.Fb&&g.dT(this.player)&&this.nB()&&!this.B};
var Phb=[1,3,2,4];g.x(r6,g.X);g.k=r6.prototype;g.k.onClick=function(a){this.I.N("web_player_log_click_before_generating_ve_conversion_params")&&this.I.ub(this.element);this.j?this.I.Qa("innertubeCommand",g.R(this.j.onTap,g.$Q)):g.tT(this.getVideoUrl(),this.I,a);this.I.N("web_player_log_click_before_generating_ve_conversion_params")||this.I.ub(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.I.getVideoUrl(a,!1,!1,!0);var b=this.I.W();if(g.rM(b)||g.AM(b)){var c={};b.Fa&&g.rM(b)&&g.DS(c,b.loaderUrl);g.rM(b)&&g.KS(this.I,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.CS(c,b);a=g.Ij(a,c)}return a};
g.k.Za=function(){this.I.Za(this.element,this.Fb&&this.ma)};
g.k.show=function(){g.X.prototype.show.call(this);this.Za()};
g.k.hide=function(){g.X.prototype.hide.call(this);this.Za()};
g.k.pc=function(a){g.X.prototype.pc.call(this,a);this.Za()};g.x(s6,n6);s6.prototype.show=function(){3!==this.player.getPlayerState()&&(n6.prototype.show.call(this),this.j.aA(!0),this.j.Br(!0),this.I.W().Lc||this.j.Ar(!0),this.I.Za(this.element,!0),this.watchButton.pc(!0))};
s6.prototype.hide=function(){n6.prototype.hide.call(this);this.j.aA(!1);this.j.Br(!1);this.j.Ar(!1);this.I.Za(this.element,!1);this.watchButton.pc(!1)};g.x(Khb,n6);Khb.prototype.Ta=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.vk;var b=this.subscribeButton;a.subscribed?b.j():b.u()};g.x(t6,g.X);t6.prototype.select=function(){this.api.jo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.JB||void 0)&&this.api.ub(this.element)};
t6.prototype.onClick=function(a){if(g.rM(this.api.W())&&this.api.N("web_player_log_click_before_generating_ve_conversion_params")){this.api.ub(this.element);var b=this.suggestion.Mk(),c={};g.dKa(this.api,c,"emb_rel_end");b=g.Ij(b,c);g.tT(b,this.api,a)}else g.sT(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
t6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.cQ(a)||(this.select(),g.dQ(a))}};
t6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.W();this.u=a.Ed?!1:b.C};g.x(u6,n6);g.k=u6.prototype;g.k.create=function(){n6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Up();this.u.T(this.player,"appresize",this.Up);this.u.T(this.player,"onVideoAreaChange",this.Up);this.u.T(this.player,"videodatachange",this.onVideoDataChange);this.u.T(this.player,"autonavchange",this.NJ);this.u.T(this.player,"autonavcancel",this.P_);a=this.videoData.autonavState;a!==this.V&&this.NJ(a);this.u.T(this.element,"transitionend",this.u8)};
g.k.destroy=function(){g.FA(this.u);g.sb(this.stills);this.stills=[];n6.prototype.destroy.call(this);g.Aq(this.element,"ytp-show-tiles");this.J.stop();this.V=this.videoData.autonavState};
g.k.nB=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.Fb;n6.prototype.show.call(this);g.Aq(this.element,"ytp-show-tiles");this.player.W().u?g.sq(this.J):this.J.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.XS(this.player,!1);v6(this)?(w6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.iA():3===this.videoData.autonavState&&this.j.lw()):(g.XS(this.player,!0),w6(this));a!==this.Fb&&this.player.Za(this.element,!0)};
g.k.hide=function(){var a=this.Fb;n6.prototype.hide.call(this);this.j.lw();w6(this);a!==this.Fb&&this.player.Za(this.element,!1)};
g.k.u8=function(a){g.bQ(a)===this.element&&this.Up()};
g.k.Up=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.AO(d)];if(e.length){g.yq(this.element,"ytp-endscreen-paginate");var f=this.I.Lk(!0,this.I.isFullscreen());if(a=g.MS(this.I))a=a.Kg()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,r=b/2,v=a<=l-2&&p>=r*n,y=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&y)p-=q*n,b+=2;else if(v)p-=r*n,a+=2;else if(y)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.An(f,n,p);g.qn(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.bF(g.AO(this.videoData));this.j instanceof
l6&&m6(this.j);g.Cq(this.element,"ytp-endscreen-takeover",v6(this));w6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,v=0,d&&l>=a-2&&m>=b-2?v=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(v=2):v=2),q=g.se(q+this.B,c),0!==v){r=this.stills[h];r||(r=new t6(this.player),this.stills[h]=r,f.appendChild(r.element));y=Math.floor(p*m/b);var A=Math.floor(n*l/a),F=Math.floor(p*(m+v)/b)-y-4,M=Math.floor(n*(l+v)/a)-A-4;g.wn(r.element,A,y);g.An(r.element,M,F);g.qn(r.element,"transitionDelay",
(m+l)/20+"s");g.Cq(r.element,"ytp-videowall-still-mini",1===v);g.Cq(r.element,"ytp-videowall-still-large",2<v);v=Math.max(M,F);g.Cq(r.element,"ytp-videowall-still-round-large",256<=v);g.Cq(r.element,"ytp-videowall-still-round-medium",96<v&&256>v);g.Cq(r.element,"ytp-videowall-still-round-small",96>=v);q=e[q];r.suggestion!==q&&(r.suggestion=q,v=r.api.W(),y=g.xq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",j6(r,q,y),g.rM(v)&&!r.api.N("web_player_log_click_before_generating_ve_conversion_params")&&
(y=q.Mk(),A={},v.Fa&&g.DS(A,v.loaderUrl),g.KS(r.api,"addEmbedsConversionTrackingParams",[A]),y=g.Ij(y,g.CS(A,"emb_rel_end")),r.updateValue("url",y)),(q=(q=q.sessionData)&&q.itct)&&r.api.eg(r.element,q));h++}f.ariaBusy="false";g.Cq(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.nf(a.element),g.qb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Up())};
g.k.Q_=function(){this.B+=this.stills.length;this.Up()};
g.k.R_=function(){this.B-=this.stills.length;this.Up()};
g.k.SV=function(){return this.j.Qk()};
g.k.NJ=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Hr(),this.Fb&&this.Up()):(this.D=!0,this.Fb&&v6(this)&&(2===a?this.j.iA():3===a&&this.j.lw()))};
g.k.P_=function(a){if(a){for(a=0;a<this.stills.length;a++)this.I.Za(this.stills[a].element,!0);this.NJ(1)}else this.C=null,this.D=!1;this.Up()};
g.k.Kf=function(){return this.Fb&&v6(this)};g.x(x6,n6);x6.prototype.show=function(){if(3!==this.player.getPlayerState()){n6.prototype.show.call(this);var a=this.u;if(a){var b=0<this.j.suggestionData.length;g.Cq(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.MS(this.player))||c.oE(!0);this.player.Za(this.element,!0);this.watchButton.pc(!0)}};
x6.prototype.hide=function(){n6.prototype.hide.call(this);var a;null==(a=g.MS(this.player))||a.oE(!1);this.player.Za(this.element,!1);this.watchButton.pc(!1)};g.x(Ohb,g.dU);g.k=Ohb.prototype;g.k.Dw=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((g.$S(this.player)||this.u)&&!b)return!0;var c;var d=!!((null==a?0:g.AO(a))||(null==a?0:null==(c=a.suggestions)?0:c.length));d=!Lhb(this.player)||d;a=a.sj||g.AM(a.Ja);c=this.player.VB();return d&&!a&&!c&&!b};
g.k.Kf=function(){return this.endScreen.Kf()};
g.k.c5=function(){return this.Kf()?this.endScreen.SV():!1};
g.k.xa=function(){this.player.Oe("endscreen");g.dU.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Eb().rf.get("heartbeat"),d=g.AO(a);!d||b.videoId!==d.videoId||a.QZ?(this.player.jo(b.videoId,void 0,void 0,!0,!0,b),c&&c.gH("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.dU.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.dU.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Dw()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Nhb(this);this.C&&Mhb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new p6(this.player):this.endScreen=new u6(this.player),g.G(this,this.endScreen),g.cT(this.player,this.endScreen.element,4))};g.cU("endscreen",Ohb);})(_yt_player);
